/**
 * constants.js - Constantes para el Cotizador V2
 * 
 * NOTA: Las categorías se mantienen centralizadas aquí, pero en un futuro cercano
 * estas vendrán dinámicamente desde una base de datos.
 */

// Array de categorías de productos con sus respectivos porcentajes de impuestos.
// Esta estructura centraliza los datos para el cálculo de impuestos.
// Los valores de impuestos se expresan como números enteros (ej: 21, 10.5, 35)
export const CATEGORIES = [
  {
    nombre: "GENERICO (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "BILLETERAS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "REPUESTOS - CABLES (34%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "REPUESTOS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "REPUESTOS (40%)",
    derechos_importacion: 16,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "HERRAMIENTAS (40%)",
    derechos_importacion: 16,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "REPUESTO FILTRO (46%)",
    derechos_importacion: 25,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
  {
    nombre: "REPUESTOS/ACCESORIOS (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "REPUESTOS P/AUTOS (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MAQUINAS ELÉCTRICAS (23%)",
    derechos_importacion: 2,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
  {
    nombre: "FUENTE DE ALIMENTACIÓN (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "LAMINAS DE ALUMINIO (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "APARATOS MECÁNICOS PARA PULVERIZAR/DISPERSAR (27%)",
    derechos_importacion: 13,
    tasa_estadistica: 3,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "INTERRUPTORES (11%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "ACCESORIOS PERSONALES (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "IMPRESORA 3D (23%)",
    derechos_importacion: 12.6,
    tasa_estadistica: 0,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "NOTEBOOK (59%)",
    derechos_importacion: 45.5,
    tasa_estadistica: 3,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "INSUMOS INFORMATICA (30%)",
    derechos_importacion: 6,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "ARTICULOS INFORMATICA (35%)",
    derechos_importacion: 14,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
  {
    nombre: "GENERICO INFORMATICA (21%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MOUSE (21%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
  {
    nombre: "CABLE USB (30%)",
    derechos_importacion: 6,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MOUSE PAD (40%)",
    derechos_importacion: 16,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "TECLADOS (11%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "SOPORTE PARA CELULAR (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "CELULARES (0%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 0,
    activa: true,
  },
  {
    nombre: "FUNDAS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "VIDRIO T. CELULAR (50%)",
    derechos_importacion: 26,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MODULOS/REPUESTOS CELULAR (32%)",
    derechos_importacion: 10.8,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
  {
    nombre: "AURICULARES (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "SMARTWATCH (11%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "AURICULARES BLUETOOTH (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "RELOJ ANALÓGICO (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MALLAS SMARTWATCH (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "TRACKERS (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "COMBO SW (11%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "TV BOX 1 (56%)",
    derechos_importacion: 32,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "TV BOX (14%)",
    derechos_importacion: 0,
    tasa_estadistica: 3,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "LÁMPARA/LUCES LED (56%)",
    derechos_importacion: 32,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "CONSOLA DE JUEGOS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "ILUMINACIÓN/SEÑALIZACIÓN PARA BICICLETAS (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "PROYECTORES (40%)",
    derechos_importacion: 26.5,
    tasa_estadistica: 3,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "GENERICO PESCA (40%)",
    derechos_importacion: 16,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "ANZUELOS (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "RULEMANES (40%)",
    derechos_importacion: 16,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "OVER GRIPS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "ARTICULOS DE COTILLON (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "PORTA VELAS (18%)",
    derechos_importacion: 18,
    tasa_estadistica: 0,
    iva: 0,
    activa: true,
  },
  {
    nombre: "ARTICULOS PARA MASCOTAS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "CEPILLOS PARA MASCOTAS (56%)",
    derechos_importacion: 32,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "BIJOUTERIE/JOYERÍA (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "LLAVEROS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MOCHILAS/BOLSOS/CARTERAS/ESTUCHES (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "MARROQUINERÍA (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "FUNDAS PARA CARTAS (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "JUGUETES (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "PERFUMEROS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "BOLSAS/CAJAS/PACKAGING (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "INDUMENTARIA (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "CALZADO (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "TEXTILES (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "VINCHAS (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "PEINE CON ESPEJO (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "COLITAS PARA PELO (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "CLIPS PARA PELO (44%)",
    derechos_importacion: 20,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "FUNDAS IMPERMEABLES PVC (42%)",
    derechos_importacion: 18,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "STICKERS UÑAS (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 2.5,
    iva: 21,
    activa: true,
  },
  {
    nombre: "TIRAS NASALES / DILATADOR NASAL (59%)",
    derechos_importacion: 35,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "INSTRUMENTOS/APARATOS PARA ANÁLISIS (23%)",
    derechos_importacion: 12.6,
    tasa_estadistica: 0,
    iva: 10.5,
    activa: true,
  },
  {
    nombre: "GENERICO (56%)",
    derechos_importacion: 32.5,
    tasa_estadistica: 3,
    iva: 21,
    activa: true,
  },
  {
    nombre: "COMISION PAGO A PROVEE (4%)",
    derechos_importacion: 3.5,
    tasa_estadistica: 0,
    iva: 0,
    activa: true,
  },
  {
    nombre: "ENVIOS PERSONALES (-400 USD) (21%)",
    derechos_importacion: 0,
    tasa_estadistica: 0,
    iva: 21,
    activa: true,
  },
];

// Caja inicial por defecto para el formulario de cajas
export const INITIAL_BOXES = [
  { id: 1, weight: 0, length: 0, width: 0, height: 0 },
];
